title: PSSnippets
description: Portable snippet management for PowerShell 7+
#theme: minima
theme: jekyll-theme-primer
url: https://soulhakr.github.io/PSSnippets
baseurl: ""
github_username: soulhakr
repository: soulhakr/PSSnippets
header_pages:
  - index.md
  - cmdlets/Get-Snippet.md
  - cmdlets/Invoke-Snippet.md
  - cmdlets/New-Snippet.md
  - cmdlets/Set-Snippet.md
  - cmdlets/Remove-Snippet.md
  - cmdlets/Export-Snippet.md
  - cmdlets/Export-SnippetToMarkdown.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - minima